!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 10, y: -1, z: 10}
      - !Vector3 {x: -1, y: -1, z: 30}
      #colors:
      #- !RGB {r: 204, g: 0, b: 204 }
      rotations: [45]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: CylinderTunnel
      #colors:
      #- !RGB {r: 204, g: 0, b: 204 }
      #- !RGB {r: 204, g: 0, b: 204 }
      #- !RGB {r: 204, g: 0, b: 204 }
    - !Item
      name: GoodGoalMultiBounce
    - !Item
      name: GoodGoalMulti
